# Generated by Django 3.1.4 on 2020-12-14 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, verbose_name='a possible answer')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512, verbose_name='a question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsAndAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False)),
                ('choices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizshow.choice')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizshow.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(through='quizshow.QuestionsAndAnswers', to='quizshow.Choice'),
        ),
        migrations.AddConstraint(
            model_name='questionsandanswers',
            constraint=models.UniqueConstraint(fields=('questions', 'choices'), name='question_and_possible_answers'),
        ),
    ]
