# Generated by Django 3.1.4 on 2020-12-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizshow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(through='quizshow.QuestionsAndAnswers', to='quizshow.Choice', verbose_name='possible answers'),
        ),
    ]
