# Generated by Django 3.1.4 on 2020-12-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizshow', '0003_auto_20201215_2035'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questionsandanswers',
            name='question_and_possible_answers',
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(through='quizshow.QuestionsAndAnswers', to='quizshow.Choice', verbose_name='possible answer'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=128, verbose_name='subject name'),
        ),
        migrations.AddConstraint(
            model_name='questionsandanswers',
            constraint=models.UniqueConstraint(fields=('questions', 'choices'), name='question_and_possible_answer'),
        ),
    ]
